# Generated by Django 3.2.5 on 2021-07-05 09:50

import book_list_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('isbn_number', models.CharField(max_length=13, validators=[book_list_app.models.isbn_validator])),
                ('page_count', models.PositiveIntegerField()),
                ('front_cover_link', models.URLField(blank=True, null=True)),
                ('language', models.CharField(max_length=45)),
            ],
        ),
    ]
