# Generated by Django 3.2.5 on 2021-07-05 10:15

import book_list_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(max_length=10, validators=[book_list_app.models.pub_date_validator]),
        ),
    ]
