# Generated by Django 3.2.5 on 2021-07-05 17:57

import book_list_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list_app', '0002_alter_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[book_list_app.models.isbn_validator]),
        ),
    ]
